### PR TITLE
Added allow clobber parameter to Packagemanagement Dsc resource.

### PR DESCRIPTION
**Pull request by AlexisColes**
Fix for issue: #310 

Seems to work ok on .net haven't tried core or standard

### CODE REVIEW

**Comment by AlexisColes** [comment]
Just realised that AllowClobber is only available on WMF 5.1... ahh nothing is ever easy!  Most of our servers are upgraded to 5.1 now, but not sure if you are happy that this version of packagemanagement takes a dependency on that :(

**Comment by brywang-msft** [comment]
First, thank you for your contribution to the DSC resource! It's great to see.

Second, I think that should be fine, as long as the docs are updated to say that ```AllowClobber``` is only available when using PackageManagement vWhatever + a minor fix to the code. When this PR does go in, please create an issue for a doc update.

Third, please do not ask to merge directly to master. You may see some direct commits for simple cherry-picks and the like, but merging to master with new changes is not a good developer practice. Please merge to WIP under normal conditions. However, we're in the middle of a small release to unblock PowerShell Core, which means WIP is blocked for non-approved changes. I've created a ```vNext``` working branch to use until WIP is free again - please submit a PR requesting to merge there.

Fourth, if possible, please try to add a test for this new functionality. Otherwise create an issue for it and we'll take care of it.

Finally, and this is more of an aside than anything, we recommend that you work in a topic branch even in your own fork:
```
git checkout WIP
git checkout -b my-fix
# Make changes
```

**Comment by AlexisColes** [comment]
Hi brywang thanks for your Welcome and feedback.  I am just getting ready for a 2 week holiday.  However I  going to do all these things when I get back.  Although I may well need pointing in the right direction with a couple of them.  Feel free to reject this pull request in the mean time and I will try to do it properly when back near a PC.

**Comment by jianyunt** [comment]
@AlexisColes  @brywang-msft I made the WIP as default branch.  Next time, if you git clone again, default will be WIP (working in progress) branch.

@AlexisColes could you please integrate the feedback from @brywang-msft and resubmit again to WIP. I am going to close this PR .
Again thank you for your contributions!

**Pull request closed without merging**
