### PR TITLE
Merge of PackageManagement DSC resources into main module

### PR DESCRIPTION
**Pull request by brywang-msft**
Merges PackageManagementProviderResource into the main PackageManagement module. Adds the DSC tests and examples. Removes Nuget and PSModule resources. run-tests.ps1 now runs Pester in two separate execution steps (main tests and DSC tests) due to conflict issues with OneGetTestProvider.

Didn't bump version or test with CI runs.

### CODE REVIEW

**Comment by brywang-msft** [comment]
Need to get PS DSC for Linux enabled in Travis CI.

**Comment by brywang-msft** [comment]
Need to fix this for Core CLR: 'Microsoft.Management.Infrastructure.Native.Unmanaged.DLL': The specified module could not be found.
  
And potentially this (but probably just related to the above DSC-related error):
  At C:\projects\oneget\Test\DSCTests\OneGetTestHelper.ps1:38 char:1

  + {

  + ~

  Unexpected token '{' in expression or statement.

  

  At C:\projects\oneget\Test\DSCTests\OneGetTestHelper.ps1:81 char:1

  + }

  + ~

  Unexpected token '}' in expression or statement.

  at <ScriptBlock>, C:\projects\oneget\Test\DSCTests\tests\OneGetSource.Get.Set.Test.Tests.ps1: line 14

[-] Error occurred in test script 'C:\projects\oneget\Test\DSCTests\tests\PackageManagement.Get.Tests.ps1' 103ms

  At C:\projects\oneget\Test\DSCTests\OneGetTestHelper.ps1:37 char:15

**Comment by jianyunt** [comment]
@ brywang-msft, You need to fix the test before merge to master branch.

**Comment by brywang-msft** [comment]
Throwing in a quick note before I keep working on this PR. We're going to skip Core CLR and Linux testing for now and work on getting them enabled ASAP (issues with DSC on Core CLR and Linux). We'll also need to add the ability to fail the test run for full CLR if any tests fail.

**Comment by jianyunt** [comment]
:shipit:

**Pull request merged**
