### PR TITLE
Fixing typo in PackageManagement/sources

### PR DESCRIPTION
**Pull request by abatishchev**
`#(OUTPUT_PATH)` -> `$(OUTPUT_PATH)`.

### CODE REVIEW

**Comment by abatishchev** [comment]
Any response please?

**Comment by abatishchev** [comment]
Any response please?

**Comment by abatishchev** [comment]
Any response please?

**Comment by fearthecowboy** [comment]
Sorry; I've been temporarily seconded to another project that's been
sucking 100%+ of my time; I'm going to see if I can squeeze some time in
this week to merge everything coming from both internal and external...


On Sat, Jul 11, 2015 at 12:36 PM, Alexander Batishchev <
notifications@github.com> wrote:

> Any response please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OneGet/oneget/pull/139#issuecomment-120654476>.
>



-- 
==============================
Garrett Serack

**Comment by jianyunt** [comment]
This should already be fixed.

**Pull request closed without merging**
