### PR TITLE
dotnet CLI 2.0 migration

### PR DESCRIPTION
**Pull request by brywang-msft**
Migration of all .csproj's owned by this repo to dotnet CLI 2.0. Verified VS build and build.ps1. Also verified package and module installation/removal in full PowerShell and PSCore beta1.

### CODE REVIEW

**Comment by jianyunt** [comment]
>         [string]$Channel = "rel-1.0.0",

do we need to update the channel too?

---
Refers to: src/bootstrap.ps1:36 in adbaa51. [](commit_id = adbaa51be8515929a8e6d8dfec8b408fcf523155, deletion_comment = False)

**Comment by jianyunt** [comment]
>     $obtainUrl = "https://raw.githubusercontent.com/dotnet/cli/9855dc0088cf7e56e24860c734f33fe8353f38a6/scripts/obtain"

this needs to be updated too

---
Refers to: src/bootstrap.ps1:83 in adbaa51. [](commit_id = adbaa51be8515929a8e6d8dfec8b408fcf523155, deletion_comment = False)

**Comment by jianyunt** [comment]
:shipit:

**Comment by brywang-msft** [comment]
Commits aren't being picked up anymore for some reason. Going to close and re-open this.

**Pull request closed without merging**
