### PR TITLE
WIP Upgrade from netcoreapp2.0 to netstandard2.0 since netcoreapp2.0 is not supported any more

### LINKED ISSUE #408: Packagemanagement is being built using .Net Core 2.0 which is not supported any more
PowerShell Core is consuming the netcoreapp2.0 binaries, it should be upgraded to 2.1, which is supported and also an LTS version
cc @SteveL-MSFT

### PR DESCRIPTION
**Pull request by bergmeister**
This is also important because PowerShell Core consumes and ships `Packagemanagement`
Fixes #408
WIP because I need to fix CI

### CODE REVIEW

**Comment by edyoung** [comment]
Hi, thanks for looking into this, appreciate the changes. 

The CI build is failing so we'll need to resolve that before we can merge. Let us know if you're able to look at the issues or if we should.

**Comment by bergmeister** [comment]
@edyoung when trying to upgrade, I encountered various problems: the SDK and NuGet references are very out of date and once I fixed that I found that the dependent submodule for the NuGet provider needs to be fixed first...
Help is appreciated but can we agree on the path first:
I propose to drop compilation for .net Core completely and replace it with netstandard2.0 instead.

**Comment by alerickson** [comment]
@bergmeister We need to make sure Package Management still supports PowerShell v3+.  Upgrading to  netcoreapp2.1 sounds like a good idea, but I'll need to look into what dropping compilation for netcore in general would do

**Comment by alerickson** [comment]
@bergmeister I need to follow up with some folks to see what Package Management still needs to support.  Our goal is to narrow down targets to just netstandard2.0 just completely get rid netcoreapp2.x and net451.

**Comment by bergmeister** [comment]
@alerickson That sounds great but at least for the project of the dll entry point, I think you will still need net451 because Windows PowerShell is too old and does not know what .net standard is

**Comment by alerickson** [comment]
@bergmeister that's one of things we're trying to figure out-- the min version of Windows PowerShell we need to support.  It's possible we can drop support for Windows PowerShell lower than 5.1.  In either case we'll try to narrow down the targets as much as feasibly possible.  I'll keep you updated as to what I learn.

**Comment by bergmeister** [comment]
Ok, I see. But the details of the `net451` compilation against Windows PowerShell is independent of the issue that PowerShell Core currently receives a build against netcoreapp2.0
Don't you agree that we should first replace the `netstandard1.6` and `netcoreapp2.0` targets with just `netstandard2.0` for the moment to resolve the issue of PowerShell Core as a consumer? Changing the requirements for Windows PowerShell seems to be unrelated to this as far as I understand.

**Comment by alerickson** [comment]
@bergmeister yes, I completely agree that we should at the very least change netstandard to 2.0, I just need to check that change won't break Windows NanoServer, which 1.6 provides support for.

**Comment by bergmeister** [comment]
@alerickson The `microsoft/powershell:nanoserver` image comes with PowerShell Core 6.1.1 but the `microsoft/nanoserver` image has a super early version of 5.1 of PowerShell Core (the name of the executable is therefore still powershell). It seems to be quite extreme trying to support a version of PowerShell Core that probably has Alpha1 quality and therefore the image should rather replace it by the latest version of PowerShell Core IMHO. cc @SteveL-MSFT

**Comment by alerickson** [comment]
@bergmeister I'm talking to someone to see if can get the latest PowerShell Core on the Nano Server image.  I think that'd be the ideal way to move forward

**Comment by bergmeister** [comment]
I will close this PR in favour of the new PR since incremental work is needed due to the lack of maintenance of this project since the whole build and test process is completely out of date.:
- old .Net SDK is being used and old Nuget packages referencing various previews, also including PSCore preview reference assemblies for Windows PowerShell (!)
- old Alpha/Beta version of PowerShell Core is being used for testing -> a PR for that is already open
- `netstandard1.6` is not even being used at runtime by PowerShell Core 6.0 or 6.1. Trying to use it does not seem to simply work...

**Pull request closed without merging**
