### PR TITLE
Create MSI and Bundle for OneGet.

### PR DESCRIPTION
**Pull request by firegiantco**
Reasonable (and working) starting point for a Bundle to install OneGet. The user still has to run `Import-Module OneGet` somewhere (maybe adding it to their `$profile`) but this installer takes care of everything else (i.e. "works on our machines").

### CODE REVIEW

**Comment by firegiantco** [comment]
These changes have be committed to the wip branch.

**Comment by paulomorgado** [comment]
Why not make part of the install adding the module to the global or user profile, depending on the installation type?

**Comment by firegiantco** [comment]
That was discussed with @fearthecowboy and @jaykul and all came to the same conclusion that modifying the profile was more problematic than requiring the user to `Import-Module OneGet`.

**Comment by Jaykul** [comment]
Yeah, the short version is: that's just not how it's done. Normally you just rely on autoloading.  Of course, OneGet is broken in that regard. 

For the record (and because maybe other module authors will read this and take it as the prescriptive advice it's meant to be):

If you are going to alter the profile, you might as well just overwrite the OneGet that's in System32 (after all, it's not like you'd be overwriting someone else's module, it's guaranteed to just be an older version of this module). Then you wouldn't need to alter the profile, because autoloading will always prefer modules in System32 regardless of PSModulePath order.

Aside from that:

1. There are (at least) six possible profile scripts on a clean Windows box (two "AllHost" profiles, and two each for PowerShell.exe and ISE). Which are executed depends on the host you use.  That means that editing someone's profile can result in great confusion for the poor user who might (for whatever reason) not ever have used that particular profile script, and might not realized it's been created (or modified).
2. Profiles can be code-signed (mine are, everyone's should be) -- in which case you'd just break them.

Finally, there's the case of the user base. In my opinion, the people who need/want to install OneGet manually instead of just using the built-in one are power users -- who are disproportionately likely to be annoyed and/or inconvenienced if you "mess with" their profile script(s). ;-)

**Comment by doctordns** [comment]
Great Summary Joel.

First, I think that OneGet just be YAM (yet another module). It does some cool things, yes, and has some interesting relationships with the OS (in terms of effectively adding features).  But those aside, OneGet should be installed into one of the standard module folders.  I hate it when any team decides to add paths to $env:psmodulepath.

I’m not clear on why Joel says OneGet is broken – I am using PowerShell V5 drop on  Server 2012 R2 (I use a server os for my workstation to enable some useful things, like full Hyper-V and SMTP!) I was able to use Find-package just fine via autoloading. Install. I am using the module installed by the V5 installer. Or am I missing something.

Turning to Joel’s point about there being 6 profiles. Given the usage scenario’s I’ve encountered at my clients and discussions in the training room, there is a wealth of approaches. If you edit any of these profiles, some percentage of the users will be unhappy. I really hate having to unpick what some random installer has done. I can cite a couple of 3rd party modules that screwed things for ME, causing unpicking to be needed.

You could argue that the majority of users will just want to install, use cmdlets and that’s it. Any module should be auto-loadable (and unloadable to the extent possible). Joel is right, it’s powerusers who will be doing the manual install – most user just want it all to just work and not screw things up.

My .02€ worth.

Thomas

**Comment by fearthecowboy** [comment]
And finally, the MSI is really just for 'experimental' releases. 

For official releases, we're going to move to a separate Windows Update ( .msu file) for OneGet so it can be applied without having to install the whole WMF to get it.

Once that's done, we'll also be on a monthly cadence for stable releases, so the MSI is really intended for the very impatient :)

**Comment by Jaykul** [comment]
Sorry, OneGet isn't broken.  The ability to upgrade and install it is broken ;-)

That is: if you download the installer from GitHub to "update" your OneGet, it has to install to either `${ENV:ProgramFiles}\WIndowsPowerShell\Modules` or `$HOME\Documents\WindowsPowerShell\Modules` but PowerShell 5 already ships a copy in System32.  The result is that if you rely on autoloading, you get the *old* version from System32, instead of the new version you installed.

That's why you have to Import-Module by hand (to load the one from your PSModulePath).

The only workaround for that (as @fearthecowboy says) is to release **official** Microsoft:tm: versions to overwrite the System32 module (via Windows Update) on a rapid cadence. Who would have thought that was possible for anything other than virus signatures?

**Comment by fearthecowboy** [comment]
@Jaykul  :)  No kidding, eh?

**Pull request closed without merging**
