### PR TITLE
Upgrade from net451 to net452 because net451 is not supported any more

### PR DESCRIPTION
**Pull request by bergmeister**
This PR depends first on [this](https://github.com/OneGet/NuGetProvider/pull/49) PR for the NuGet provider to complete. This PR currently points to this PR branch to demonstrate that it works end to end, I will repoint the submodule after the dependent PR has been completed.

### CODE REVIEW

**Comment by alerickson** [comment]
@bergmeister I'll push the NuGet Provider development branch into master and these builds should start working again

**Comment by bergmeister** [comment]
Ok, thanks, I was not aware that the submodule points to master. Let me know when you are done and then I'll update the submodule pointer again. P.S. Why is the `Nugetprovider` as submodule? Ideally, it should be merged into this repo

**Comment by alerickson** [comment]
No need to update the submodule!  The default is master, I just needed to merge your updates there.  
To be quite honest, I'm not quite sure why NuGet Provider is still a submodule.  I'm onboard with consolidating and simplifying Package Management though.  Don't think it's necessary at all to keep it as a submodule.

**Comment by bergmeister** [comment]
The way submodules work is that one has to update the pointer to them, that's one of the reasons why it makes it so tedious having to work with submodules, therefore once you push to master, I need to update where the submodule points to since one cannot point it at the latest point in a branch.

**Comment by alerickson** [comment]
@bergmeister ah okay!  Was hoping the update would be enough.  NuGet Provider is merged into master now though.

**Comment by bergmeister** [comment]
@alerickson No worries, I updated the submodule pointer and the build is green now :-)

**Pull request merged**
